import type { Business } from "./types";

// Sample businesses for Phase 1. Replace/extend via the admin (Phase 4) once
// Supabase is live. No Google review text or hours are stored here by design.
const now = "2026-09-10T00:00:00.000Z";

export const BUSINESSES: Business[] = [
  {
    id: "b001",
    slug: "coastline-plumbing-co",
    name: "Coastline Plumbing Co.",
    trade: "plumbing",
    secondary_trades: [],
    city: "Long Beach",
    county: "Los Angeles",
    service_areas: ["Long Beach", "Lakewood", "Signal Hill"],
    keywords: [
      "drain cleaning",
      "water heater",
      "tankless",
      "repipe",
      "leak repair",
      "emergency plumber",
      "sewer",
    ],
    address: "1200 E Broadway, Long Beach, CA 90802",
    latitude: 33.7695,
    longitude: -118.1826,
    phone: "+15625550110",
    email: "service@coastlineplumbing.example",
    website: "https://coastlineplumbing.example",
    google_place_id: null,
    short_description: "Licensed plumbers for repairs, repipes, and water heaters.",
    long_description:
      "Coastline Plumbing has served the Long Beach area for over 20 years. We handle leak repairs, drain cleaning, tankless water heater installs, and full repipes. Family owned and fully licensed.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b002",
    slug: "sunpeak-electrical",
    name: "SunPeak Electrical",
    trade: "electrical",
    secondary_trades: [],
    city: "Irvine",
    county: "Orange",
    service_areas: ["Irvine", "Tustin", "Costa Mesa"],
    address: "45 Technology Dr, Irvine, CA 92618",
    latitude: 33.6503,
    longitude: -117.7448,
    phone: "+19495550142",
    email: "hello@sunpeakelectric.example",
    website: "https://sunpeakelectric.example",
    google_place_id: null,
    short_description: "Panel upgrades, EV chargers, and whole-home rewiring.",
    long_description:
      "SunPeak Electrical specializes in residential panel upgrades, EV charger installation, and lighting. Certified electricians, upfront pricing, and same-week scheduling across Orange County.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b003",
    slug: "desert-air-hvac",
    name: "Desert Air Heating & Cooling",
    trade: "hvac",
    secondary_trades: [],
    city: "Palm Springs",
    county: "Riverside",
    service_areas: ["Palm Springs", "Cathedral City", "Rancho Mirage"],
    keywords: [
      "ac repair",
      "air conditioning",
      "heat pump",
      "mini split",
      "furnace",
      "hvac installation",
      "thermostat",
    ],
    address: "500 S Palm Canyon Dr, Palm Springs, CA 92264",
    latitude: 33.8153,
    longitude: -116.5453,
    phone: "+17605550188",
    email: "info@desertairhvac.example",
    website: "https://desertairhvac.example",
    google_place_id: null,
    short_description: "AC repair and new installs built for desert heat.",
    long_description:
      "Desert Air keeps homes cool through the hottest months. We service and install high-efficiency AC systems, heat pumps, and mini-splits throughout the Coachella Valley.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b004",
    slug: "summit-roofing-sd",
    name: "Summit Roofing",
    trade: "roofing",
    secondary_trades: ["restoration-services"],
    city: "San Diego",
    county: "San Diego",
    service_areas: ["San Diego", "La Mesa", "Chula Vista"],
    address: "3300 University Ave, San Diego, CA 92104",
    latitude: 32.7484,
    longitude: -117.1281,
    phone: "+16195550163",
    email: "quotes@summitroofing.example",
    website: "https://summitroofing.example",
    google_place_id: null,
    short_description: "Re-roofs, repairs, and storm damage restoration.",
    long_description:
      "Summit Roofing installs shingle, tile, and flat roofing systems. We also handle leak repairs and insurance storm-damage work across San Diego County.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b005",
    slug: "greenline-landscaping",
    name: "GreenLine Landscaping",
    trade: "landscaping",
    secondary_trades: ["concrete-masonry"],
    city: "Ventura",
    county: "Ventura",
    service_areas: ["Ventura", "Oxnard", "Camarillo"],
    address: "2100 E Main St, Ventura, CA 93001",
    latitude: 34.2783,
    longitude: -119.2765,
    phone: "+18055550176",
    email: "team@greenlineland.example",
    website: "https://greenlineland.example",
    google_place_id: null,
    short_description: "Drought-friendly yards, hardscape, and irrigation.",
    long_description:
      "GreenLine designs and builds low-water landscapes, paver patios, retaining walls, and smart irrigation. Serving Ventura County homeowners and property managers.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b006",
    slug: "truecoat-painting",
    name: "TrueCoat Painting",
    trade: "painting",
    secondary_trades: ["remodelers"],
    city: "Pasadena",
    county: "Los Angeles",
    service_areas: ["Pasadena", "Arcadia", "Glendale"],
    address: "88 W Colorado Blvd, Pasadena, CA 91105",
    latitude: 34.1459,
    longitude: -118.1526,
    phone: "+16265550119",
    email: "book@truecoatpaint.example",
    website: "https://truecoatpaint.example",
    google_place_id: null,
    short_description: "Interior and exterior painting with clean prep work.",
    long_description:
      "TrueCoat handles interior repaints, exterior jobs, cabinet refinishing, and stucco. Careful prep, drop-cloth clean workmanship, and a written warranty on every job.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b007",
    slug: "inland-concrete-masonry",
    name: "Inland Concrete & Masonry",
    trade: "concrete-masonry",
    secondary_trades: ["paving"],
    city: "Riverside",
    county: "Riverside",
    service_areas: ["Riverside", "Moreno Valley", "Corona"],
    address: "3900 Main St, Riverside, CA 92501",
    latitude: 33.9825,
    longitude: -117.3742,
    phone: "+19515550154",
    email: "estimate@inlandconcrete.example",
    website: "https://inlandconcrete.example",
    google_place_id: null,
    short_description: "Driveways, foundations, block walls, and pavers.",
    long_description:
      "Inland Concrete pours driveways, walkways, patios, and foundations, and builds block and brick walls. Serving the Inland Empire with dependable crews.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b010",
    slug: "valley-power-generators",
    name: "Valley Power & Generators",
    trade: "generator-services",
    secondary_trades: ["electrical"],
    city: "El Centro",
    county: "Imperial",
    service_areas: ["El Centro", "Brawley", "Calexico"],
    address: "500 Main St, El Centro, CA 92243",
    latitude: 32.792,
    longitude: -115.5631,
    phone: "+17605550171",
    email: "office@valleypower.example",
    website: "https://valleypower.example",
    google_place_id: null,
    short_description: "Standby generator installs, service, and repairs.",
    long_description:
      "Valley Power installs and services whole-home and commercial standby generators, transfer switches, and portable units. Licensed technicians serving the Imperial Valley.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b011",
    slug: "harbor-garage-doors",
    name: "Harbor Garage Doors",
    trade: "garage-doors",
    secondary_trades: [],
    city: "Anaheim",
    county: "Orange",
    service_areas: ["Anaheim", "Fullerton", "Orange"],
    address: "1500 S Anaheim Blvd, Anaheim, CA 92805",
    latitude: 33.8206,
    longitude: -117.9126,
    phone: "+17145550128",
    email: "service@harborgarage.example",
    website: "https://harborgarage.example",
    google_place_id: null,
    short_description: "Spring repair, opener installs, and new doors.",
    long_description:
      "Harbor Garage Doors fixes broken springs, replaces openers, and installs new insulated doors. Same-day repair across north Orange County.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "b012",
    slug: "clearview-restoration",
    name: "ClearView Restoration",
    trade: "restoration-services",
    secondary_trades: ["remodelers"],
    city: "Torrance",
    county: "Los Angeles",
    service_areas: ["Torrance", "Redondo Beach", "Gardena"],
    address: "2200 Sepulveda Blvd, Torrance, CA 90501",
    latitude: 33.8358,
    longitude: -118.3406,
    phone: "+13105550185",
    email: "help@clearviewrestore.example",
    website: "https://clearviewrestore.example",
    google_place_id: null,
    short_description: "Water, fire, and mold damage cleanup and rebuild.",
    long_description:
      "ClearView Restoration responds to water, fire, and mold emergencies, then rebuilds. We coordinate directly with insurance and are available 24/7 across the South Bay.",
    logo_url: null,
    photo_urls: [],
    status: "published",
    claimed_by: null,
    claimed_at: null,
    created_at: now,
    updated_at: now,
  },
];
