// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

// Static output. Dynamic pieces (live status, claim flow, email) run as
// standalone Netlify Functions under netlify/functions, not Astro SSR.
//
// The sitemap is generated by src/pages/sitemap-index.xml.ts and
// sitemap-0.xml.ts (not @astrojs/sitemap) so it can exclude noindex/thin
// category pages and claim pages and add a per-URL <lastmod>. See src/lib/seo.ts.
export default defineConfig({
  // Production domain. Used for canonical tags and sitemap generation.
  site: 'https://socaltrades.net',
  output: 'static',
  vite: {
    plugins: [tailwindcss()],
  },
});
